dist: trusty
sudo: true
language: node_js
install: true
branches:
  only:
    - master
    - UserInterface
before_script:
  - echo "Current Directory:"
  - pwd
  - echo "Changing directories to user-interface folder..."
  - cd "$TRAVIS_BUILD_DIR/homebase/user-interface/"
  - echo "Current Directory:"
  - pwd
  - echo "Installing dependencies..."
  - npm install 
script:
  - echo "Running lint before executing unit tests..."
  - npm run lint
  - echo "Running unit tests..."
  - npm run test
after_success:
  - echo "Successfully linted and ran unit tests!"
  - echo "Now reporting code coverage to codecov..."
  - npm run report-coverage
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/homebase/user-interface/node_modules"
notifications:
  slack: titanrover:P4c9djaMXyBBxi2DL7BwMYUE
